apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcamp
  labels:
    tier: frontend

spec:
  replicas: 2
  selector: 
    matchLabels:
      tier:  frontend

  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: bootcamp
          image: gcr.io/google-samples/kubernetes-bootcamp:v1
    
