apiVersion: v1
kind: Service
metadata:
  name: bootcamp-service
  namespace: default
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 900
    nodePort: 30010
  selector:
    tier: frontend